#!/bin/bash

if ! [ -x "$(command -v go)" ]; then
  echo 'Error: "go" is not installed.' >&2
  exit 1
fi

rm -rf ./bin
mkdir ./bin
go build -o ./bin ./cmd/mt-gen
sudo cp ./bin/mt-gen /usr/bin
rm -rf ./bin

rm -rf ~/mt-gen
mkdir ~/mt-gen
cp -r templates ~/mt-gen
