#!/bin/bash

if ! [ -x "$(command -v go)" ]; then
  echo 'Error: "go" is not installed.' >&2
  exit 1
fi

go mod tidy

rm -rf ./bin
mkdir ./bin
go build -o ./bin ./cmd/mt-gen
if [[ "$OSTYPE" == "darwin"* ]]; then
  sudo cp ./bin/mt-gen /usr/local/bin/
else
  sudo cp ./bin/mt-gen /usr/bin/
fi
rm -rf ./bin

rm -rf ~/mt-gen
mkdir ~/mt-gen
cp -r templates ~/mt-gen
