// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// Email email
//
// swagger:model Email
type Email strfmt.Email

// Validate validates this email
func (m Email) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.FormatOf("", "body", "email", strfmt.Email(m).String(), formats); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
