// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// Language language
//
// swagger:model Language
type Language string

const (

	// LanguageEn captures enum value "en"
	LanguageEn Language = "en"

	// LanguageFr captures enum value "fr"
	LanguageFr Language = "fr"
)

// for schema
var languageEnum []interface{}

func init() {
	var res []Language
	if err := json.Unmarshal([]byte(`["en","fr"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		languageEnum = append(languageEnum, v)
	}
}

func (m Language) validateLanguageEnum(path, location string, value Language) error {
	if err := validate.EnumCase(path, location, value, languageEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this language
func (m Language) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.MinLength("", "body", string(m), 2); err != nil {
		return err
	}

	if err := validate.MaxLength("", "body", string(m), 2); err != nil {
		return err
	}

	// value enum
	if err := m.validateLanguageEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
