// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// Password password
//
// swagger:model Password
type Password string

// Validate validates this password
func (m Password) Validate(formats strfmt.Registry) error {
	return nil
}
