// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// Phone phone
//
// swagger:model Phone
type Phone string

// Validate validates this phone
func (m Phone) Validate(formats strfmt.Registry) error {
	return nil
}
