// Code generated by mtgroup-generator.
package app

// Make sure not to overwrite this file after you generated it because all your edits would be lost!

import "errors"

// Errors.
var (
	ErrNotFound          = errors.New("not found")
	ErrNotFoundArrayItem = errors.New("not found array item")
	ErrDuplicateID       = errors.New("duplicate ID value")
	ErrAccessDenied      = errors.New("insufficient access rights")
)
