// Code generated by mtgroup-generator.
package app

// Make sure not to overwrite this file after you generated it because all your edits would be lost!

// Authz describes user roles/permissions.
type Authz struct {
	User    bool
	Admin   bool
	Manager bool
}

// Profile describes user profile returned by /get-user-profile.
type Profile struct {
	ID               string
	Authn            bool
	Authz            Authz
	IsolatedEntityID string
}
