name: "Demo"
module: "Demo"
description: "demo generated app"
auth-srv: "github.com/Lisss13/french-back-template/auth-service/mtmb-extauthapi"
models:
  location:
    description: "location object"
    columns: 
      id:
        type: "uuid"
      name:
        type: "string"
    methods:
      - add
  company:
    description: "company object"
    detailed-pagination: true
    id-from-profile: true
    return-when-edit: true
    columns:
      id: 
        type: "uuid"
      name:
        type: "string"
        sort-on: true
      occupation:
        type: "string"
        sort-on: true
      location:
        type: "model.location"
    methods:
      - get
      - add
      - delete
      - edit
      - list
  employe:
    description: "employe object"
    tags:
      - Employe
    columns:
      id: 
        type: "uuid"
      name:
        type: "string"
      department:
        type: "string"
      company:
        type: "model.company"
    methods: 
      - add
      - edit
      - list
      - list(id,name, company(name, location(id, name)))
      - custom