name: "Demo"
module: "Demo"
description: "demo generated app"
auth-srv: "github.com/mtgroupit/mt-back-generator/extauthapi"
models:
  location:
    description: "location object"
    columns: 
      id:
        type: "uuid"
      name:
        type: "string"
    methods:
      - add
  company:
    description: "company object"
    detailed-pagination: true
    id-from-profile: true
    return-when-edit: true
    columns:
      id: 
        type: "uuid"
      name:
        type: "string"
        sort-on: true
      occupation:
        type: "string"
        sort-on: true
      headOfficeLocation:
        type: "model.location"
      locations:
        type: "[]model.location"
    methods:
      - get
      - add
      - delete
      - edit(occupation, locations)
      - list
  employe:
    description: "employe object"
    tags:
      - Employe
    columns:
      id: 
        type: "uuid"
      name:
        type: "string"
        sort-on: true
      department:
        type: "string"
      company:
        type: "model.company"
        sort-on: true
        sort-by:
          - occupation
          - headOfficeLocation.name
    methods: 
      - add
      - edit
      - list
      - list(id, name*, company*(name, locations(id, name)))
      - custom