// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mtgroupit/mt-back-generator/extauthapi/models"
)

// GetUserProfileReader is a Reader for the GetUserProfile structure.
type GetUserProfileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetUserProfileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetUserProfileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetUserProfileDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetUserProfileOK creates a GetUserProfileOK with default headers values
func NewGetUserProfileOK() *GetUserProfileOK {
	return &GetUserProfileOK{}
}

/*GetUserProfileOK handles this case with default header values.

OK
*/
type GetUserProfileOK struct {
	Payload *models.Profile
}

func (o *GetUserProfileOK) Error() string {
	return fmt.Sprintf("[POST /get-user-profile][%d] getUserProfileOK  %+v", 200, o.Payload)
}

func (o *GetUserProfileOK) GetPayload() *models.Profile {
	return o.Payload
}

func (o *GetUserProfileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Profile)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUserProfileDefault creates a GetUserProfileDefault with default headers values
func NewGetUserProfileDefault(code int) *GetUserProfileDefault {
	return &GetUserProfileDefault{
		_statusCode: code,
	}
}

/*GetUserProfileDefault handles this case with default header values.

Generic error response.
*/
type GetUserProfileDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get user profile default response
func (o *GetUserProfileDefault) Code() int {
	return o._statusCode
}

func (o *GetUserProfileDefault) Error() string {
	return fmt.Sprintf("[POST /get-user-profile][%d] getUserProfile default  %+v", o._statusCode, o.Payload)
}

func (o *GetUserProfileDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetUserProfileDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
