// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/Lisss13/french-back-template/snouki-mobile/mtmb-extauthapi/models"
)

// GetUserProfileByIDReader is a Reader for the GetUserProfileByID structure.
type GetUserProfileByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetUserProfileByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetUserProfileByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetUserProfileByIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetUserProfileByIDOK creates a GetUserProfileByIDOK with default headers values
func NewGetUserProfileByIDOK() *GetUserProfileByIDOK {
	return &GetUserProfileByIDOK{}
}

/*GetUserProfileByIDOK handles this case with default header values.

OK
*/
type GetUserProfileByIDOK struct {
	Payload *models.Profile
}

func (o *GetUserProfileByIDOK) Error() string {
	return fmt.Sprintf("[POST /get-user-profile-by-id][%d] getUserProfileByIdOK  %+v", 200, o.Payload)
}

func (o *GetUserProfileByIDOK) GetPayload() *models.Profile {
	return o.Payload
}

func (o *GetUserProfileByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Profile)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUserProfileByIDDefault creates a GetUserProfileByIDDefault with default headers values
func NewGetUserProfileByIDDefault(code int) *GetUserProfileByIDDefault {
	return &GetUserProfileByIDDefault{
		_statusCode: code,
	}
}

/*GetUserProfileByIDDefault handles this case with default header values.

Generic error response.
*/
type GetUserProfileByIDDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get user profile by ID default response
func (o *GetUserProfileByIDDefault) Code() int {
	return o._statusCode
}

func (o *GetUserProfileByIDDefault) Error() string {
	return fmt.Sprintf("[POST /get-user-profile-by-id][%d] getUserProfileByID default  %+v", o._statusCode, o.Payload)
}

func (o *GetUserProfileByIDDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetUserProfileByIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetUserProfileByIDBody get user profile by ID body
swagger:model GetUserProfileByIDBody
*/
type GetUserProfileByIDBody struct {

	// id
	// Required: true
	// Format: uuid4
	ID models.UserID `json:"id"`
}

// Validate validates this get user profile by ID body
func (o *GetUserProfileByIDBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetUserProfileByIDBody) validateID(formats strfmt.Registry) error {

	if err := o.ID.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("args" + "." + "id")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetUserProfileByIDBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetUserProfileByIDBody) UnmarshalBinary(b []byte) error {
	var res GetUserProfileByIDBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
