// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetUserProfileByIDParams creates a new GetUserProfileByIDParams object
// with the default values initialized.
func NewGetUserProfileByIDParams() *GetUserProfileByIDParams {
	var ()
	return &GetUserProfileByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetUserProfileByIDParamsWithTimeout creates a new GetUserProfileByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetUserProfileByIDParamsWithTimeout(timeout time.Duration) *GetUserProfileByIDParams {
	var ()
	return &GetUserProfileByIDParams{

		timeout: timeout,
	}
}

// NewGetUserProfileByIDParamsWithContext creates a new GetUserProfileByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetUserProfileByIDParamsWithContext(ctx context.Context) *GetUserProfileByIDParams {
	var ()
	return &GetUserProfileByIDParams{

		Context: ctx,
	}
}

// NewGetUserProfileByIDParamsWithHTTPClient creates a new GetUserProfileByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetUserProfileByIDParamsWithHTTPClient(client *http.Client) *GetUserProfileByIDParams {
	var ()
	return &GetUserProfileByIDParams{
		HTTPClient: client,
	}
}

/*GetUserProfileByIDParams contains all the parameters to send to the API endpoint
for the get user profile by ID operation typically these are written to a http.Request
*/
type GetUserProfileByIDParams struct {

	/*Args*/
	Args GetUserProfileByIDBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get user profile by ID params
func (o *GetUserProfileByIDParams) WithTimeout(timeout time.Duration) *GetUserProfileByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get user profile by ID params
func (o *GetUserProfileByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get user profile by ID params
func (o *GetUserProfileByIDParams) WithContext(ctx context.Context) *GetUserProfileByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get user profile by ID params
func (o *GetUserProfileByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get user profile by ID params
func (o *GetUserProfileByIDParams) WithHTTPClient(client *http.Client) *GetUserProfileByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get user profile by ID params
func (o *GetUserProfileByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithArgs adds the args to the get user profile by ID params
func (o *GetUserProfileByIDParams) WithArgs(args GetUserProfileByIDBody) *GetUserProfileByIDParams {
	o.SetArgs(args)
	return o
}

// SetArgs adds the args to the get user profile by ID params
func (o *GetUserProfileByIDParams) SetArgs(args GetUserProfileByIDBody) {
	o.Args = args
}

// WriteToRequest writes these params to a swagger request
func (o *GetUserProfileByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Args); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
