// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewIsEmailAvailableParams creates a new IsEmailAvailableParams object
// with the default values initialized.
func NewIsEmailAvailableParams() *IsEmailAvailableParams {
	var ()
	return &IsEmailAvailableParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewIsEmailAvailableParamsWithTimeout creates a new IsEmailAvailableParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewIsEmailAvailableParamsWithTimeout(timeout time.Duration) *IsEmailAvailableParams {
	var ()
	return &IsEmailAvailableParams{

		timeout: timeout,
	}
}

// NewIsEmailAvailableParamsWithContext creates a new IsEmailAvailableParams object
// with the default values initialized, and the ability to set a context for a request
func NewIsEmailAvailableParamsWithContext(ctx context.Context) *IsEmailAvailableParams {
	var ()
	return &IsEmailAvailableParams{

		Context: ctx,
	}
}

// NewIsEmailAvailableParamsWithHTTPClient creates a new IsEmailAvailableParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewIsEmailAvailableParamsWithHTTPClient(client *http.Client) *IsEmailAvailableParams {
	var ()
	return &IsEmailAvailableParams{
		HTTPClient: client,
	}
}

/*IsEmailAvailableParams contains all the parameters to send to the API endpoint
for the is email available operation typically these are written to a http.Request
*/
type IsEmailAvailableParams struct {

	/*Args*/
	Args IsEmailAvailableBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the is email available params
func (o *IsEmailAvailableParams) WithTimeout(timeout time.Duration) *IsEmailAvailableParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the is email available params
func (o *IsEmailAvailableParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the is email available params
func (o *IsEmailAvailableParams) WithContext(ctx context.Context) *IsEmailAvailableParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the is email available params
func (o *IsEmailAvailableParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the is email available params
func (o *IsEmailAvailableParams) WithHTTPClient(client *http.Client) *IsEmailAvailableParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the is email available params
func (o *IsEmailAvailableParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithArgs adds the args to the is email available params
func (o *IsEmailAvailableParams) WithArgs(args IsEmailAvailableBody) *IsEmailAvailableParams {
	o.SetArgs(args)
	return o
}

// SetArgs adds the args to the is email available params
func (o *IsEmailAvailableParams) SetArgs(args IsEmailAvailableBody) {
	o.Args = args
}

// WriteToRequest writes these params to a swagger request
func (o *IsEmailAvailableParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Args); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
