// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewIsUsernameAvailableParams creates a new IsUsernameAvailableParams object
// with the default values initialized.
func NewIsUsernameAvailableParams() *IsUsernameAvailableParams {
	var ()
	return &IsUsernameAvailableParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewIsUsernameAvailableParamsWithTimeout creates a new IsUsernameAvailableParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewIsUsernameAvailableParamsWithTimeout(timeout time.Duration) *IsUsernameAvailableParams {
	var ()
	return &IsUsernameAvailableParams{

		timeout: timeout,
	}
}

// NewIsUsernameAvailableParamsWithContext creates a new IsUsernameAvailableParams object
// with the default values initialized, and the ability to set a context for a request
func NewIsUsernameAvailableParamsWithContext(ctx context.Context) *IsUsernameAvailableParams {
	var ()
	return &IsUsernameAvailableParams{

		Context: ctx,
	}
}

// NewIsUsernameAvailableParamsWithHTTPClient creates a new IsUsernameAvailableParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewIsUsernameAvailableParamsWithHTTPClient(client *http.Client) *IsUsernameAvailableParams {
	var ()
	return &IsUsernameAvailableParams{
		HTTPClient: client,
	}
}

/*IsUsernameAvailableParams contains all the parameters to send to the API endpoint
for the is username available operation typically these are written to a http.Request
*/
type IsUsernameAvailableParams struct {

	/*Args*/
	Args IsUsernameAvailableBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the is username available params
func (o *IsUsernameAvailableParams) WithTimeout(timeout time.Duration) *IsUsernameAvailableParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the is username available params
func (o *IsUsernameAvailableParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the is username available params
func (o *IsUsernameAvailableParams) WithContext(ctx context.Context) *IsUsernameAvailableParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the is username available params
func (o *IsUsernameAvailableParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the is username available params
func (o *IsUsernameAvailableParams) WithHTTPClient(client *http.Client) *IsUsernameAvailableParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the is username available params
func (o *IsUsernameAvailableParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithArgs adds the args to the is username available params
func (o *IsUsernameAvailableParams) WithArgs(args IsUsernameAvailableBody) *IsUsernameAvailableParams {
	o.SetArgs(args)
	return o
}

// SetArgs adds the args to the is username available params
func (o *IsUsernameAvailableParams) SetArgs(args IsUsernameAvailableBody) {
	o.Args = args
}

// WriteToRequest writes these params to a swagger request
func (o *IsUsernameAvailableParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Args); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
