// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRegisterActivateResendEmailParams creates a new RegisterActivateResendEmailParams object
// with the default values initialized.
func NewRegisterActivateResendEmailParams() *RegisterActivateResendEmailParams {
	var ()
	return &RegisterActivateResendEmailParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRegisterActivateResendEmailParamsWithTimeout creates a new RegisterActivateResendEmailParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRegisterActivateResendEmailParamsWithTimeout(timeout time.Duration) *RegisterActivateResendEmailParams {
	var ()
	return &RegisterActivateResendEmailParams{

		timeout: timeout,
	}
}

// NewRegisterActivateResendEmailParamsWithContext creates a new RegisterActivateResendEmailParams object
// with the default values initialized, and the ability to set a context for a request
func NewRegisterActivateResendEmailParamsWithContext(ctx context.Context) *RegisterActivateResendEmailParams {
	var ()
	return &RegisterActivateResendEmailParams{

		Context: ctx,
	}
}

// NewRegisterActivateResendEmailParamsWithHTTPClient creates a new RegisterActivateResendEmailParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRegisterActivateResendEmailParamsWithHTTPClient(client *http.Client) *RegisterActivateResendEmailParams {
	var ()
	return &RegisterActivateResendEmailParams{
		HTTPClient: client,
	}
}

/*RegisterActivateResendEmailParams contains all the parameters to send to the API endpoint
for the register activate resend email operation typically these are written to a http.Request
*/
type RegisterActivateResendEmailParams struct {

	/*Args*/
	Args RegisterActivateResendEmailBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the register activate resend email params
func (o *RegisterActivateResendEmailParams) WithTimeout(timeout time.Duration) *RegisterActivateResendEmailParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the register activate resend email params
func (o *RegisterActivateResendEmailParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the register activate resend email params
func (o *RegisterActivateResendEmailParams) WithContext(ctx context.Context) *RegisterActivateResendEmailParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the register activate resend email params
func (o *RegisterActivateResendEmailParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the register activate resend email params
func (o *RegisterActivateResendEmailParams) WithHTTPClient(client *http.Client) *RegisterActivateResendEmailParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the register activate resend email params
func (o *RegisterActivateResendEmailParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithArgs adds the args to the register activate resend email params
func (o *RegisterActivateResendEmailParams) WithArgs(args RegisterActivateResendEmailBody) *RegisterActivateResendEmailParams {
	o.SetArgs(args)
	return o
}

// SetArgs adds the args to the register activate resend email params
func (o *RegisterActivateResendEmailParams) SetArgs(args RegisterActivateResendEmailBody) {
	o.Args = args
}

// WriteToRequest writes these params to a swagger request
func (o *RegisterActivateResendEmailParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Args); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
