// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/mtgroupit/mt-back-generator/extauthapi/models"
)

// RequestRegistrationReader is a Reader for the RequestRegistration structure.
type RequestRegistrationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RequestRegistrationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewRequestRegistrationNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewRequestRegistrationDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRequestRegistrationNoContent creates a RequestRegistrationNoContent with default headers values
func NewRequestRegistrationNoContent() *RequestRegistrationNoContent {
	return &RequestRegistrationNoContent{}
}

/*RequestRegistrationNoContent handles this case with default header values.

The server successfully processed the request and is not returning any content.
*/
type RequestRegistrationNoContent struct {
}

func (o *RequestRegistrationNoContent) Error() string {
	return fmt.Sprintf("[POST /request-registration][%d] requestRegistrationNoContent ", 204)
}

func (o *RequestRegistrationNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRequestRegistrationDefault creates a RequestRegistrationDefault with default headers values
func NewRequestRegistrationDefault(code int) *RequestRegistrationDefault {
	return &RequestRegistrationDefault{
		_statusCode: code,
	}
}

/*RequestRegistrationDefault handles this case with default header values.

- 404.2003: email is not available
- 404.2004: password is too weak

*/
type RequestRegistrationDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the request registration default response
func (o *RequestRegistrationDefault) Code() int {
	return o._statusCode
}

func (o *RequestRegistrationDefault) Error() string {
	return fmt.Sprintf("[POST /request-registration][%d] requestRegistration default  %+v", o._statusCode, o.Payload)
}

func (o *RequestRegistrationDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *RequestRegistrationDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*RequestRegistrationBody request registration body
swagger:model RequestRegistrationBody
*/
type RequestRegistrationBody struct {

	// email
	// Required: true
	// Format: email
	Email models.Email `json:"email"`

	// language
	Language models.Language `json:"language,omitempty"`

	// password
	// Required: true
	Password models.Password `json:"password"`
}

// Validate validates this request registration body
func (o *RequestRegistrationBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateLanguage(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validatePassword(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *RequestRegistrationBody) validateEmail(formats strfmt.Registry) error {

	if err := o.Email.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("args" + "." + "email")
		}
		return err
	}

	return nil
}

func (o *RequestRegistrationBody) validateLanguage(formats strfmt.Registry) error {

	if swag.IsZero(o.Language) { // not required
		return nil
	}

	if err := o.Language.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("args" + "." + "language")
		}
		return err
	}

	return nil
}

func (o *RequestRegistrationBody) validatePassword(formats strfmt.Registry) error {

	if err := o.Password.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("args" + "." + "password")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *RequestRegistrationBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *RequestRegistrationBody) UnmarshalBinary(b []byte) error {
	var res RequestRegistrationBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
