// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSearchUsersByUsernameParams creates a new SearchUsersByUsernameParams object
// with the default values initialized.
func NewSearchUsersByUsernameParams() *SearchUsersByUsernameParams {
	var ()
	return &SearchUsersByUsernameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSearchUsersByUsernameParamsWithTimeout creates a new SearchUsersByUsernameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSearchUsersByUsernameParamsWithTimeout(timeout time.Duration) *SearchUsersByUsernameParams {
	var ()
	return &SearchUsersByUsernameParams{

		timeout: timeout,
	}
}

// NewSearchUsersByUsernameParamsWithContext creates a new SearchUsersByUsernameParams object
// with the default values initialized, and the ability to set a context for a request
func NewSearchUsersByUsernameParamsWithContext(ctx context.Context) *SearchUsersByUsernameParams {
	var ()
	return &SearchUsersByUsernameParams{

		Context: ctx,
	}
}

// NewSearchUsersByUsernameParamsWithHTTPClient creates a new SearchUsersByUsernameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSearchUsersByUsernameParamsWithHTTPClient(client *http.Client) *SearchUsersByUsernameParams {
	var ()
	return &SearchUsersByUsernameParams{
		HTTPClient: client,
	}
}

/*SearchUsersByUsernameParams contains all the parameters to send to the API endpoint
for the search users by username operation typically these are written to a http.Request
*/
type SearchUsersByUsernameParams struct {

	/*Args*/
	Args SearchUsersByUsernameBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the search users by username params
func (o *SearchUsersByUsernameParams) WithTimeout(timeout time.Duration) *SearchUsersByUsernameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the search users by username params
func (o *SearchUsersByUsernameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the search users by username params
func (o *SearchUsersByUsernameParams) WithContext(ctx context.Context) *SearchUsersByUsernameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the search users by username params
func (o *SearchUsersByUsernameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the search users by username params
func (o *SearchUsersByUsernameParams) WithHTTPClient(client *http.Client) *SearchUsersByUsernameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the search users by username params
func (o *SearchUsersByUsernameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithArgs adds the args to the search users by username params
func (o *SearchUsersByUsernameParams) WithArgs(args SearchUsersByUsernameBody) *SearchUsersByUsernameParams {
	o.SetArgs(args)
	return o
}

// SetArgs adds the args to the search users by username params
func (o *SearchUsersByUsernameParams) SetArgs(args SearchUsersByUsernameBody) {
	o.Args = args
}

// WriteToRequest writes these params to a swagger request
func (o *SearchUsersByUsernameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Args); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
