// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSetNewPasswordParams creates a new SetNewPasswordParams object
// with the default values initialized.
func NewSetNewPasswordParams() *SetNewPasswordParams {
	var ()
	return &SetNewPasswordParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSetNewPasswordParamsWithTimeout creates a new SetNewPasswordParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSetNewPasswordParamsWithTimeout(timeout time.Duration) *SetNewPasswordParams {
	var ()
	return &SetNewPasswordParams{

		timeout: timeout,
	}
}

// NewSetNewPasswordParamsWithContext creates a new SetNewPasswordParams object
// with the default values initialized, and the ability to set a context for a request
func NewSetNewPasswordParamsWithContext(ctx context.Context) *SetNewPasswordParams {
	var ()
	return &SetNewPasswordParams{

		Context: ctx,
	}
}

// NewSetNewPasswordParamsWithHTTPClient creates a new SetNewPasswordParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSetNewPasswordParamsWithHTTPClient(client *http.Client) *SetNewPasswordParams {
	var ()
	return &SetNewPasswordParams{
		HTTPClient: client,
	}
}

/*SetNewPasswordParams contains all the parameters to send to the API endpoint
for the set new password operation typically these are written to a http.Request
*/
type SetNewPasswordParams struct {

	/*Args*/
	Args SetNewPasswordBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the set new password params
func (o *SetNewPasswordParams) WithTimeout(timeout time.Duration) *SetNewPasswordParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set new password params
func (o *SetNewPasswordParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set new password params
func (o *SetNewPasswordParams) WithContext(ctx context.Context) *SetNewPasswordParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set new password params
func (o *SetNewPasswordParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set new password params
func (o *SetNewPasswordParams) WithHTTPClient(client *http.Client) *SetNewPasswordParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set new password params
func (o *SetNewPasswordParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithArgs adds the args to the set new password params
func (o *SetNewPasswordParams) WithArgs(args SetNewPasswordBody) *SetNewPasswordParams {
	o.SetArgs(args)
	return o
}

// SetArgs adds the args to the set new password params
func (o *SetNewPasswordParams) SetArgs(args SetNewPasswordBody) {
	o.Args = args
}

// WriteToRequest writes these params to a swagger request
func (o *SetNewPasswordParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Args); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
