// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/mtgroupit/mt-back-generator/extauthapi/models"
)

// SetEmailReader is a Reader for the SetEmail structure.
type SetEmailReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetEmailReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewSetEmailNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewSetEmailDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSetEmailNoContent creates a SetEmailNoContent with default headers values
func NewSetEmailNoContent() *SetEmailNoContent {
	return &SetEmailNoContent{}
}

/*SetEmailNoContent handles this case with default header values.

The server successfully processed the request and is not returning any content.
*/
type SetEmailNoContent struct {
}

func (o *SetEmailNoContent) Error() string {
	return fmt.Sprintf("[POST /set-email][%d] setEmailNoContent ", 204)
}

func (o *SetEmailNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSetEmailDefault creates a SetEmailDefault with default headers values
func NewSetEmailDefault(code int) *SetEmailDefault {
	return &SetEmailDefault{
		_statusCode: code,
	}
}

/*SetEmailDefault handles this case with default header values.

- 409.700: email is not available
- 409.709: invalid email validation token

*/
type SetEmailDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the set email default response
func (o *SetEmailDefault) Code() int {
	return o._statusCode
}

func (o *SetEmailDefault) Error() string {
	return fmt.Sprintf("[POST /set-email][%d] setEmail default  %+v", o._statusCode, o.Payload)
}

func (o *SetEmailDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *SetEmailDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*SetEmailBody set email body
swagger:model SetEmailBody
*/
type SetEmailBody struct {

	// email token
	// Required: true
	EmailToken models.JWT `json:"emailToken"`
}

// Validate validates this set email body
func (o *SetEmailBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateEmailToken(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SetEmailBody) validateEmailToken(formats strfmt.Registry) error {

	if err := o.EmailToken.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("args" + "." + "emailToken")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *SetEmailBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SetEmailBody) UnmarshalBinary(b []byte) error {
	var res SetEmailBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
