// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/mtgroupit/mt-back-generator/extauthapi/models"
)

// SetBlockedReader is a Reader for the SetBlocked structure.
type SetBlockedReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetBlockedReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewSetBlockedNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewSetBlockedDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSetBlockedNoContent creates a SetBlockedNoContent with default headers values
func NewSetBlockedNoContent() *SetBlockedNoContent {
	return &SetBlockedNoContent{}
}

/*SetBlockedNoContent handles this case with default header values.

The server successfully processed the request and is not returning any content.
*/
type SetBlockedNoContent struct {
}

func (o *SetBlockedNoContent) Error() string {
	return fmt.Sprintf("[POST /set-blocked][%d] setBlockedNoContent ", 204)
}

func (o *SetBlockedNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSetBlockedDefault creates a SetBlockedDefault with default headers values
func NewSetBlockedDefault(code int) *SetBlockedDefault {
	return &SetBlockedDefault{
		_statusCode: code,
	}
}

/*SetBlockedDefault handles this case with default header values.

Generic error response.
*/
type SetBlockedDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the set blocked default response
func (o *SetBlockedDefault) Code() int {
	return o._statusCode
}

func (o *SetBlockedDefault) Error() string {
	return fmt.Sprintf("[POST /set-blocked][%d] setBlocked default  %+v", o._statusCode, o.Payload)
}

func (o *SetBlockedDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *SetBlockedDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*SetBlockedBody set blocked body
swagger:model SetBlockedBody
*/
type SetBlockedBody struct {

	// True to block user, False to unblock.
	// Required: true
	Blocked *bool `json:"blocked"`

	// id
	// Required: true
	// Format: uuid4
	ID models.UserID `json:"id"`
}

// Validate validates this set blocked body
func (o *SetBlockedBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateBlocked(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SetBlockedBody) validateBlocked(formats strfmt.Registry) error {

	if err := validate.Required("args"+"."+"blocked", "body", o.Blocked); err != nil {
		return err
	}

	return nil
}

func (o *SetBlockedBody) validateID(formats strfmt.Registry) error {

	if err := o.ID.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("args" + "." + "id")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *SetBlockedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SetBlockedBody) UnmarshalBinary(b []byte) error {
	var res SetBlockedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
