// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSetBlockedParams creates a new SetBlockedParams object
// with the default values initialized.
func NewSetBlockedParams() *SetBlockedParams {
	var ()
	return &SetBlockedParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSetBlockedParamsWithTimeout creates a new SetBlockedParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSetBlockedParamsWithTimeout(timeout time.Duration) *SetBlockedParams {
	var ()
	return &SetBlockedParams{

		timeout: timeout,
	}
}

// NewSetBlockedParamsWithContext creates a new SetBlockedParams object
// with the default values initialized, and the ability to set a context for a request
func NewSetBlockedParamsWithContext(ctx context.Context) *SetBlockedParams {
	var ()
	return &SetBlockedParams{

		Context: ctx,
	}
}

// NewSetBlockedParamsWithHTTPClient creates a new SetBlockedParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSetBlockedParamsWithHTTPClient(client *http.Client) *SetBlockedParams {
	var ()
	return &SetBlockedParams{
		HTTPClient: client,
	}
}

/*SetBlockedParams contains all the parameters to send to the API endpoint
for the set blocked operation typically these are written to a http.Request
*/
type SetBlockedParams struct {

	/*Args*/
	Args SetBlockedBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the set blocked params
func (o *SetBlockedParams) WithTimeout(timeout time.Duration) *SetBlockedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set blocked params
func (o *SetBlockedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set blocked params
func (o *SetBlockedParams) WithContext(ctx context.Context) *SetBlockedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set blocked params
func (o *SetBlockedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set blocked params
func (o *SetBlockedParams) WithHTTPClient(client *http.Client) *SetBlockedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set blocked params
func (o *SetBlockedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithArgs adds the args to the set blocked params
func (o *SetBlockedParams) WithArgs(args SetBlockedBody) *SetBlockedParams {
	o.SetArgs(args)
	return o
}

// SetArgs adds the args to the set blocked params
func (o *SetBlockedParams) SetArgs(args SetBlockedBody) {
	o.Args = args
}

// WriteToRequest writes these params to a swagger request
func (o *SetBlockedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Args); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
