// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSetUsernameParams creates a new SetUsernameParams object
// with the default values initialized.
func NewSetUsernameParams() *SetUsernameParams {
	var ()
	return &SetUsernameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSetUsernameParamsWithTimeout creates a new SetUsernameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSetUsernameParamsWithTimeout(timeout time.Duration) *SetUsernameParams {
	var ()
	return &SetUsernameParams{

		timeout: timeout,
	}
}

// NewSetUsernameParamsWithContext creates a new SetUsernameParams object
// with the default values initialized, and the ability to set a context for a request
func NewSetUsernameParamsWithContext(ctx context.Context) *SetUsernameParams {
	var ()
	return &SetUsernameParams{

		Context: ctx,
	}
}

// NewSetUsernameParamsWithHTTPClient creates a new SetUsernameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSetUsernameParamsWithHTTPClient(client *http.Client) *SetUsernameParams {
	var ()
	return &SetUsernameParams{
		HTTPClient: client,
	}
}

/*SetUsernameParams contains all the parameters to send to the API endpoint
for the set username operation typically these are written to a http.Request
*/
type SetUsernameParams struct {

	/*Args*/
	Args SetUsernameBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the set username params
func (o *SetUsernameParams) WithTimeout(timeout time.Duration) *SetUsernameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set username params
func (o *SetUsernameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set username params
func (o *SetUsernameParams) WithContext(ctx context.Context) *SetUsernameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set username params
func (o *SetUsernameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set username params
func (o *SetUsernameParams) WithHTTPClient(client *http.Client) *SetUsernameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set username params
func (o *SetUsernameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithArgs adds the args to the set username params
func (o *SetUsernameParams) WithArgs(args SetUsernameBody) *SetUsernameParams {
	o.SetArgs(args)
	return o
}

// SetArgs adds the args to the set username params
func (o *SetUsernameParams) SetArgs(args SetUsernameBody) {
	o.Args = args
}

// WriteToRequest writes these params to a swagger request
func (o *SetUsernameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Args); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
