// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewValidateRegistrationEmailParams creates a new ValidateRegistrationEmailParams object
// with the default values initialized.
func NewValidateRegistrationEmailParams() *ValidateRegistrationEmailParams {
	var ()
	return &ValidateRegistrationEmailParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewValidateRegistrationEmailParamsWithTimeout creates a new ValidateRegistrationEmailParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewValidateRegistrationEmailParamsWithTimeout(timeout time.Duration) *ValidateRegistrationEmailParams {
	var ()
	return &ValidateRegistrationEmailParams{

		timeout: timeout,
	}
}

// NewValidateRegistrationEmailParamsWithContext creates a new ValidateRegistrationEmailParams object
// with the default values initialized, and the ability to set a context for a request
func NewValidateRegistrationEmailParamsWithContext(ctx context.Context) *ValidateRegistrationEmailParams {
	var ()
	return &ValidateRegistrationEmailParams{

		Context: ctx,
	}
}

// NewValidateRegistrationEmailParamsWithHTTPClient creates a new ValidateRegistrationEmailParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewValidateRegistrationEmailParamsWithHTTPClient(client *http.Client) *ValidateRegistrationEmailParams {
	var ()
	return &ValidateRegistrationEmailParams{
		HTTPClient: client,
	}
}

/*ValidateRegistrationEmailParams contains all the parameters to send to the API endpoint
for the validate registration email operation typically these are written to a http.Request
*/
type ValidateRegistrationEmailParams struct {

	/*Args*/
	Args ValidateRegistrationEmailBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the validate registration email params
func (o *ValidateRegistrationEmailParams) WithTimeout(timeout time.Duration) *ValidateRegistrationEmailParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the validate registration email params
func (o *ValidateRegistrationEmailParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the validate registration email params
func (o *ValidateRegistrationEmailParams) WithContext(ctx context.Context) *ValidateRegistrationEmailParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the validate registration email params
func (o *ValidateRegistrationEmailParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the validate registration email params
func (o *ValidateRegistrationEmailParams) WithHTTPClient(client *http.Client) *ValidateRegistrationEmailParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the validate registration email params
func (o *ValidateRegistrationEmailParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithArgs adds the args to the validate registration email params
func (o *ValidateRegistrationEmailParams) WithArgs(args ValidateRegistrationEmailBody) *ValidateRegistrationEmailParams {
	o.SetArgs(args)
	return o
}

// SetArgs adds the args to the validate registration email params
func (o *ValidateRegistrationEmailParams) SetArgs(args ValidateRegistrationEmailBody) {
	o.Args = args
}

// WriteToRequest writes these params to a swagger request
func (o *ValidateRegistrationEmailParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Args); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
