// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/mtgroupit/mt-back-generator/extauthapi/models"
)

// ValidateNewEmailReader is a Reader for the ValidateNewEmail structure.
type ValidateNewEmailReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ValidateNewEmailReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewValidateNewEmailNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewValidateNewEmailDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewValidateNewEmailNoContent creates a ValidateNewEmailNoContent with default headers values
func NewValidateNewEmailNoContent() *ValidateNewEmailNoContent {
	return &ValidateNewEmailNoContent{}
}

/*ValidateNewEmailNoContent handles this case with default header values.

The server successfully processed the request and is not returning any content.
*/
type ValidateNewEmailNoContent struct {
}

func (o *ValidateNewEmailNoContent) Error() string {
	return fmt.Sprintf("[POST /validate-new-email][%d] validateNewEmailNoContent ", 204)
}

func (o *ValidateNewEmailNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewValidateNewEmailDefault creates a ValidateNewEmailDefault with default headers values
func NewValidateNewEmailDefault(code int) *ValidateNewEmailDefault {
	return &ValidateNewEmailDefault{
		_statusCode: code,
	}
}

/*ValidateNewEmailDefault handles this case with default header values.

- 409.700: email is not available
- 403.710: invalid password

*/
type ValidateNewEmailDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the validate new email default response
func (o *ValidateNewEmailDefault) Code() int {
	return o._statusCode
}

func (o *ValidateNewEmailDefault) Error() string {
	return fmt.Sprintf("[POST /validate-new-email][%d] validateNewEmail default  %+v", o._statusCode, o.Payload)
}

func (o *ValidateNewEmailDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *ValidateNewEmailDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*ValidateNewEmailBody validate new email body
swagger:model ValidateNewEmailBody
*/
type ValidateNewEmailBody struct {

	// email
	// Required: true
	// Format: email
	Email models.Email `json:"email"`

	// password
	// Required: true
	Password models.Password `json:"password"`
}

// Validate validates this validate new email body
func (o *ValidateNewEmailBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validatePassword(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ValidateNewEmailBody) validateEmail(formats strfmt.Registry) error {

	if err := o.Email.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("args" + "." + "email")
		}
		return err
	}

	return nil
}

func (o *ValidateNewEmailBody) validatePassword(formats strfmt.Registry) error {

	if err := o.Password.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("args" + "." + "password")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *ValidateNewEmailBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ValidateNewEmailBody) UnmarshalBinary(b []byte) error {
	var res ValidateNewEmailBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
