// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Authentication
//
//  ## List of all custom errors
//  First number is HTTP Status code, second is value of "code" field in returned JSON object, text description may or may not match "message" field in returned JSON object.
//  - 404.101: invalid credentials
//
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /api/v1/
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
