// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/mtgroupit/mt-back-generator/extauthapi/models"
)

// ChangePasswordNoContentCode is the HTTP code returned for type ChangePasswordNoContent
const ChangePasswordNoContentCode int = 204

/*ChangePasswordNoContent The server successfully processed the request and is not returning any content.

swagger:response changePasswordNoContent
*/
type ChangePasswordNoContent struct {
	/*Session token.

	 */
	SetCookie string `json:"Set-Cookie"`
}

// NewChangePasswordNoContent creates ChangePasswordNoContent with default headers values
func NewChangePasswordNoContent() *ChangePasswordNoContent {

	return &ChangePasswordNoContent{}
}

// WithSetCookie adds the setCookie to the change password no content response
func (o *ChangePasswordNoContent) WithSetCookie(setCookie string) *ChangePasswordNoContent {
	o.SetCookie = setCookie
	return o
}

// SetSetCookie sets the setCookie to the change password no content response
func (o *ChangePasswordNoContent) SetSetCookie(setCookie string) {
	o.SetCookie = setCookie
}

// WriteResponse to the client
func (o *ChangePasswordNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Set-Cookie

	setCookie := o.SetCookie
	if setCookie != "" {
		rw.Header().Set("Set-Cookie", setCookie)
	}

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*ChangePasswordDefault - 422.702: password is too weak
- 403.710: invalid password


swagger:response changePasswordDefault
*/
type ChangePasswordDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewChangePasswordDefault creates ChangePasswordDefault with default headers values
func NewChangePasswordDefault(code int) *ChangePasswordDefault {
	if code <= 0 {
		code = 500
	}

	return &ChangePasswordDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the change password default response
func (o *ChangePasswordDefault) WithStatusCode(code int) *ChangePasswordDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the change password default response
func (o *ChangePasswordDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the change password default response
func (o *ChangePasswordDefault) WithPayload(payload *models.Error) *ChangePasswordDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the change password default response
func (o *ChangePasswordDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ChangePasswordDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
