// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/mtgroupit/mt-back-generator/extauthapi/models"
)

// ChangePasswordHandlerFunc turns a function with the right signature into a change password handler
type ChangePasswordHandlerFunc func(ChangePasswordParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ChangePasswordHandlerFunc) Handle(params ChangePasswordParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ChangePasswordHandler interface for that can handle valid change password params
type ChangePasswordHandler interface {
	Handle(ChangePasswordParams, interface{}) middleware.Responder
}

// NewChangePassword creates a new http.Handler for the change password operation
func NewChangePassword(ctx *middleware.Context, handler ChangePasswordHandler) *ChangePassword {
	return &ChangePassword{Context: ctx, Handler: handler}
}

/*ChangePassword swagger:route POST /change-password changePassword

Change user password and expire all user sessions including current one.

*/
type ChangePassword struct {
	Context *middleware.Context
	Handler ChangePasswordHandler
}

func (o *ChangePassword) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewChangePasswordParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// ChangePasswordBody change password body
//
// swagger:model ChangePasswordBody
type ChangePasswordBody struct {

	// new password
	// Required: true
	NewPassword models.Password `json:"newPassword"`

	// old password
	OldPassword models.Password `json:"oldPassword,omitempty"`
}

// Validate validates this change password body
func (o *ChangePasswordBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateNewPassword(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateOldPassword(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ChangePasswordBody) validateNewPassword(formats strfmt.Registry) error {

	if err := o.NewPassword.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("args" + "." + "newPassword")
		}
		return err
	}

	return nil
}

func (o *ChangePasswordBody) validateOldPassword(formats strfmt.Registry) error {

	if swag.IsZero(o.OldPassword) { // not required
		return nil
	}

	if err := o.OldPassword.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("args" + "." + "oldPassword")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *ChangePasswordBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ChangePasswordBody) UnmarshalBinary(b []byte) error {
	var res ChangePasswordBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
