// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/mtgroupit/mt-back-generator/extauthapi/models"
)

// GetUserProfileByIDOKCode is the HTTP code returned for type GetUserProfileByIDOK
const GetUserProfileByIDOKCode int = 200

/*GetUserProfileByIDOK OK

swagger:response getUserProfileByIdOK
*/
type GetUserProfileByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Profile `json:"body,omitempty"`
}

// NewGetUserProfileByIDOK creates GetUserProfileByIDOK with default headers values
func NewGetUserProfileByIDOK() *GetUserProfileByIDOK {

	return &GetUserProfileByIDOK{}
}

// WithPayload adds the payload to the get user profile by Id o k response
func (o *GetUserProfileByIDOK) WithPayload(payload *models.Profile) *GetUserProfileByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user profile by Id o k response
func (o *GetUserProfileByIDOK) SetPayload(payload *models.Profile) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserProfileByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetUserProfileByIDDefault Generic error response.

swagger:response getUserProfileByIdDefault
*/
type GetUserProfileByIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetUserProfileByIDDefault creates GetUserProfileByIDDefault with default headers values
func NewGetUserProfileByIDDefault(code int) *GetUserProfileByIDDefault {
	if code <= 0 {
		code = 500
	}

	return &GetUserProfileByIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get user profile by ID default response
func (o *GetUserProfileByIDDefault) WithStatusCode(code int) *GetUserProfileByIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get user profile by ID default response
func (o *GetUserProfileByIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get user profile by ID default response
func (o *GetUserProfileByIDDefault) WithPayload(payload *models.Error) *GetUserProfileByIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user profile by ID default response
func (o *GetUserProfileByIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserProfileByIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
