// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Lisss13/french-back-template/snouki-mobile/mtmb-extauthapi/models"
)

// GetUserProfileOKCode is the HTTP code returned for type GetUserProfileOK
const GetUserProfileOKCode int = 200

/*GetUserProfileOK OK

swagger:response getUserProfileOK
*/
type GetUserProfileOK struct {

	/*
	  In: Body
	*/
	Payload *models.Profile `json:"body,omitempty"`
}

// NewGetUserProfileOK creates GetUserProfileOK with default headers values
func NewGetUserProfileOK() *GetUserProfileOK {

	return &GetUserProfileOK{}
}

// WithPayload adds the payload to the get user profile o k response
func (o *GetUserProfileOK) WithPayload(payload *models.Profile) *GetUserProfileOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user profile o k response
func (o *GetUserProfileOK) SetPayload(payload *models.Profile) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserProfileOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetUserProfileDefault Generic error response.

swagger:response getUserProfileDefault
*/
type GetUserProfileDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetUserProfileDefault creates GetUserProfileDefault with default headers values
func NewGetUserProfileDefault(code int) *GetUserProfileDefault {
	if code <= 0 {
		code = 500
	}

	return &GetUserProfileDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get user profile default response
func (o *GetUserProfileDefault) WithStatusCode(code int) *GetUserProfileDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get user profile default response
func (o *GetUserProfileDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get user profile default response
func (o *GetUserProfileDefault) WithPayload(payload *models.Error) *GetUserProfileDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user profile default response
func (o *GetUserProfileDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserProfileDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
