// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetUserProfileHandlerFunc turns a function with the right signature into a get user profile handler
type GetUserProfileHandlerFunc func(GetUserProfileParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetUserProfileHandlerFunc) Handle(params GetUserProfileParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetUserProfileHandler interface for that can handle valid get user profile params
type GetUserProfileHandler interface {
	Handle(GetUserProfileParams, interface{}) middleware.Responder
}

// NewGetUserProfile creates a new http.Handler for the get user profile operation
func NewGetUserProfile(ctx *middleware.Context, handler GetUserProfileHandler) *GetUserProfile {
	return &GetUserProfile{Context: ctx, Handler: handler}
}

/*GetUserProfile swagger:route POST /get-user-profile getUserProfile

Get user profile.

*/
type GetUserProfile struct {
	Context *middleware.Context
	Handler GetUserProfileHandler
}

func (o *GetUserProfile) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetUserProfileParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
