// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/Lisss13/french-back-template/snouki-mobile/mtmb-extauthapi/models"
)

// IsEmailAvailableHandlerFunc turns a function with the right signature into a is email available handler
type IsEmailAvailableHandlerFunc func(IsEmailAvailableParams) middleware.Responder

// Handle executing the request and returning a response
func (fn IsEmailAvailableHandlerFunc) Handle(params IsEmailAvailableParams) middleware.Responder {
	return fn(params)
}

// IsEmailAvailableHandler interface for that can handle valid is email available params
type IsEmailAvailableHandler interface {
	Handle(IsEmailAvailableParams) middleware.Responder
}

// NewIsEmailAvailable creates a new http.Handler for the is email available operation
func NewIsEmailAvailable(ctx *middleware.Context, handler IsEmailAvailableHandler) *IsEmailAvailable {
	return &IsEmailAvailable{Context: ctx, Handler: handler}
}

/*IsEmailAvailable swagger:route POST /is-email-available isEmailAvailable

Checks is email is available.

*/
type IsEmailAvailable struct {
	Context *middleware.Context
	Handler IsEmailAvailableHandler
}

func (o *IsEmailAvailable) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewIsEmailAvailableParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// IsEmailAvailableBody is email available body
//
// swagger:model IsEmailAvailableBody
type IsEmailAvailableBody struct {

	// email
	// Required: true
	// Format: email
	Email models.Email `json:"email"`
}

// Validate validates this is email available body
func (o *IsEmailAvailableBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *IsEmailAvailableBody) validateEmail(formats strfmt.Registry) error {

	if err := o.Email.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("args" + "." + "email")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *IsEmailAvailableBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *IsEmailAvailableBody) UnmarshalBinary(b []byte) error {
	var res IsEmailAvailableBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// IsEmailAvailableOKBody is email available o k body
//
// swagger:model IsEmailAvailableOKBody
type IsEmailAvailableOKBody struct {

	// True if email is available.
	// Required: true
	Available *bool `json:"available"`
}

// Validate validates this is email available o k body
func (o *IsEmailAvailableOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateAvailable(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *IsEmailAvailableOKBody) validateAvailable(formats strfmt.Registry) error {

	if err := validate.Required("isEmailAvailableOK"+"."+"available", "body", o.Available); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *IsEmailAvailableOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *IsEmailAvailableOKBody) UnmarshalBinary(b []byte) error {
	var res IsEmailAvailableOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
