// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/mtgroupit/mt-back-generator/extauthapi/models"
)

// RegisterActivateResendEmailHandlerFunc turns a function with the right signature into a register activate resend email handler
type RegisterActivateResendEmailHandlerFunc func(RegisterActivateResendEmailParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RegisterActivateResendEmailHandlerFunc) Handle(params RegisterActivateResendEmailParams) middleware.Responder {
	return fn(params)
}

// RegisterActivateResendEmailHandler interface for that can handle valid register activate resend email params
type RegisterActivateResendEmailHandler interface {
	Handle(RegisterActivateResendEmailParams) middleware.Responder
}

// NewRegisterActivateResendEmail creates a new http.Handler for the register activate resend email operation
func NewRegisterActivateResendEmail(ctx *middleware.Context, handler RegisterActivateResendEmailHandler) *RegisterResendEmail {
	return &RegisterResendEmail{Context: ctx, Handler: handler}
}

/*RegisterResendEmail swagger:route POST /register-activate-resend-email registerActivateResendEmail

Resend new email if old token is not valid.

*/
type RegisterResendEmail struct {
	Context *middleware.Context
	Handler RegisterActivateResendEmailHandler
}

func (o *RegisterResendEmail) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRegisterActivateResendEmailParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// RegisterActivateResendEmailBody register activate resend email body
//
// swagger:model RegisterActivateResendEmailBody
type RegisterActivateResendEmailBody struct {

	// email token
	// Required: true
	EmailToken models.JWT `json:"emailToken"`
}

// Validate validates this register activate resend email body
func (o *RegisterActivateResendEmailBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateEmailToken(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *RegisterActivateResendEmailBody) validateEmailToken(formats strfmt.Registry) error {

	if err := o.EmailToken.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("args" + "." + "emailToken")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *RegisterActivateResendEmailBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *RegisterActivateResendEmailBody) UnmarshalBinary(b []byte) error {
	var res RegisterActivateResendEmailBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
