// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/mtgroupit/mt-back-generator/extauthapi/models"
)

// RegisterActivateResendEmailOKCode is the HTTP code returned for type RegisterActivateResendEmailOK
const RegisterActivateResendEmailOKCode int = 200

/*RegisterActivateResendEmailOK OK

swagger:response registerActivateResendEmailOK
*/
type RegisterActivateResendEmailOK struct {
}

// NewRegisterActivateResendEmailOK creates RegisterActivateResendEmailOK with default headers values
func NewRegisterActivateResendEmailOK() *RegisterActivateResendEmailOK {

	return &RegisterActivateResendEmailOK{}
}

// WriteResponse to the client
func (o *RegisterActivateResendEmailOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*RegisterActivateResendEmailDefault - 404.2001: invalid email validation token


swagger:response registerActivateResendEmailDefault
*/
type RegisterActivateResendEmailDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRegisterActivateResendEmailDefault creates RegisterActivateResendEmailDefault with default headers values
func NewRegisterActivateResendEmailDefault(code int) *RegisterActivateResendEmailDefault {
	if code <= 0 {
		code = 500
	}

	return &RegisterActivateResendEmailDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the register activate resend email default response
func (o *RegisterActivateResendEmailDefault) WithStatusCode(code int) *RegisterActivateResendEmailDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the register activate resend email default response
func (o *RegisterActivateResendEmailDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the register activate resend email default response
func (o *RegisterActivateResendEmailDefault) WithPayload(payload *models.Error) *RegisterActivateResendEmailDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the register activate resend email default response
func (o *RegisterActivateResendEmailDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RegisterActivateResendEmailDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
