// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/mtgroupit/mt-back-generator/extauthapi/models"
)

// RequestRegistrationNoContentCode is the HTTP code returned for type RequestRegistrationNoContent
const RequestRegistrationNoContentCode int = 204

/*RequestRegistrationNoContent The server successfully processed the request and is not returning any content.

swagger:response requestRegistrationNoContent
*/
type RequestRegistrationNoContent struct {
}

// NewRequestRegistrationNoContent creates RequestRegistrationNoContent with default headers values
func NewRequestRegistrationNoContent() *RequestRegistrationNoContent {

	return &RequestRegistrationNoContent{}
}

// WriteResponse to the client
func (o *RequestRegistrationNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*RequestRegistrationDefault - 404.2003: email is not available
- 404.2004: password is too weak


swagger:response requestRegistrationDefault
*/
type RequestRegistrationDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRequestRegistrationDefault creates RequestRegistrationDefault with default headers values
func NewRequestRegistrationDefault(code int) *RequestRegistrationDefault {
	if code <= 0 {
		code = 500
	}

	return &RequestRegistrationDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the request registration default response
func (o *RequestRegistrationDefault) WithStatusCode(code int) *RequestRegistrationDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the request registration default response
func (o *RequestRegistrationDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the request registration default response
func (o *RequestRegistrationDefault) WithPayload(payload *models.Error) *RequestRegistrationDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the request registration default response
func (o *RequestRegistrationDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RequestRegistrationDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
