// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/mtgroupit/mt-back-generator/extauthapi/models"
)

// SetPersDataRegionOKCode is the HTTP code returned for type SetPersDataRegionOK
const SetPersDataRegionOKCode int = 200

/*SetPersDataRegionOK OK

swagger:response setPersDataRegionOK
*/
type SetPersDataRegionOK struct {

	/*
	  In: Body
	*/
	Payload *SetPersDataRegionOKBody `json:"body,omitempty"`
}

// NewSetPersDataRegionOK creates SetPersDataRegionOK with default headers values
func NewSetPersDataRegionOK() *SetPersDataRegionOK {

	return &SetPersDataRegionOK{}
}

// WithPayload adds the payload to the set pers data region o k response
func (o *SetPersDataRegionOK) WithPayload(payload *SetPersDataRegionOKBody) *SetPersDataRegionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the set pers data region o k response
func (o *SetPersDataRegionOK) SetPayload(payload *SetPersDataRegionOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SetPersDataRegionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*SetPersDataRegionDefault Generic error response.

swagger:response setPersDataRegionDefault
*/
type SetPersDataRegionDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSetPersDataRegionDefault creates SetPersDataRegionDefault with default headers values
func NewSetPersDataRegionDefault(code int) *SetPersDataRegionDefault {
	if code <= 0 {
		code = 500
	}

	return &SetPersDataRegionDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the set pers data region default response
func (o *SetPersDataRegionDefault) WithStatusCode(code int) *SetPersDataRegionDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the set pers data region default response
func (o *SetPersDataRegionDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the set pers data region default response
func (o *SetPersDataRegionDefault) WithPayload(payload *models.Error) *SetPersDataRegionDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the set pers data region default response
func (o *SetPersDataRegionDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SetPersDataRegionDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
