// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/mtgroupit/mt-back-generator/extauthapi/models"
)

// SetUsernameNoContentCode is the HTTP code returned for type SetUsernameNoContent
const SetUsernameNoContentCode int = 204

/*SetUsernameNoContent The server successfully processed the request and is not returning any content.

swagger:response setUsernameNoContent
*/
type SetUsernameNoContent struct {
}

// NewSetUsernameNoContent creates SetUsernameNoContent with default headers values
func NewSetUsernameNoContent() *SetUsernameNoContent {

	return &SetUsernameNoContent{}
}

// WriteResponse to the client
func (o *SetUsernameNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*SetUsernameDefault - 409.701: username is not available


swagger:response setUsernameDefault
*/
type SetUsernameDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSetUsernameDefault creates SetUsernameDefault with default headers values
func NewSetUsernameDefault(code int) *SetUsernameDefault {
	if code <= 0 {
		code = 500
	}

	return &SetUsernameDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the set username default response
func (o *SetUsernameDefault) WithStatusCode(code int) *SetUsernameDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the set username default response
func (o *SetUsernameDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the set username default response
func (o *SetUsernameDefault) WithPayload(payload *models.Error) *SetUsernameDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the set username default response
func (o *SetUsernameDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SetUsernameDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
