// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/Lisss13/french-back-template/snouki-mobile/mtmb-extauthapi/models"
)

// ValidateNewEmailHandlerFunc turns a function with the right signature into a validate new email handler
type ValidateNewEmailHandlerFunc func(ValidateNewEmailParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ValidateNewEmailHandlerFunc) Handle(params ValidateNewEmailParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ValidateNewEmailHandler interface for that can handle valid validate new email params
type ValidateNewEmailHandler interface {
	Handle(ValidateNewEmailParams, interface{}) middleware.Responder
}

// NewValidateNewEmail creates a new http.Handler for the validate new email operation
func NewValidateNewEmail(ctx *middleware.Context, handler ValidateNewEmailHandler) *ValidateNewEmail {
	return &ValidateNewEmail{Context: ctx, Handler: handler}
}

/*ValidateNewEmail swagger:route POST /validate-new-email validateNewEmail

Request user email change.

*/
type ValidateNewEmail struct {
	Context *middleware.Context
	Handler ValidateNewEmailHandler
}

func (o *ValidateNewEmail) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewValidateNewEmailParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// ValidateNewEmailBody validate new email body
//
// swagger:model ValidateNewEmailBody
type ValidateNewEmailBody struct {

	// email
	// Required: true
	// Format: email
	Email models.Email `json:"email"`

	// password
	// Required: true
	Password models.Password `json:"password"`
}

// Validate validates this validate new email body
func (o *ValidateNewEmailBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validatePassword(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ValidateNewEmailBody) validateEmail(formats strfmt.Registry) error {

	if err := o.Email.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("args" + "." + "email")
		}
		return err
	}

	return nil
}

func (o *ValidateNewEmailBody) validatePassword(formats strfmt.Registry) error {

	if err := o.Password.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("args" + "." + "password")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *ValidateNewEmailBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ValidateNewEmailBody) UnmarshalBinary(b []byte) error {
	var res ValidateNewEmailBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
