// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/mtgroupit/mt-back-generator/extauthapi/models"
)

// ValidateRegistrationEmailHandlerFunc turns a function with the right signature into a validate registration email handler
type ValidateRegistrationEmailHandlerFunc func(ValidateRegistrationEmailParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ValidateRegistrationEmailHandlerFunc) Handle(params ValidateRegistrationEmailParams) middleware.Responder {
	return fn(params)
}

// ValidateRegistrationEmailHandler interface for that can handle valid validate registration email params
type ValidateRegistrationEmailHandler interface {
	Handle(ValidateRegistrationEmailParams) middleware.Responder
}

// NewValidateRegistrationEmail creates a new http.Handler for the validate registration email operation
func NewValidateRegistrationEmail(ctx *middleware.Context, handler ValidateRegistrationEmailHandler) *ValidateRegistrationEmail {
	return &ValidateRegistrationEmail{Context: ctx, Handler: handler}
}

/*ValidateRegistrationEmail swagger:route POST /validate-registration-email validateRegistrationEmail

Sends email with validation token.

*/
type ValidateRegistrationEmail struct {
	Context *middleware.Context
	Handler ValidateRegistrationEmailHandler
}

func (o *ValidateRegistrationEmail) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewValidateRegistrationEmailParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// ValidateRegistrationEmailBody validate registration email body
//
// swagger:model ValidateRegistrationEmailBody
type ValidateRegistrationEmailBody struct {

	// email
	// Required: true
	// Format: email
	Email models.Email `json:"email"`
}

// Validate validates this validate registration email body
func (o *ValidateRegistrationEmailBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ValidateRegistrationEmailBody) validateEmail(formats strfmt.Registry) error {

	if err := o.Email.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("args" + "." + "email")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *ValidateRegistrationEmailBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ValidateRegistrationEmailBody) UnmarshalBinary(b []byte) error {
	var res ValidateRegistrationEmailBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
