// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/mtgroupit/mt-back-generator/extauthapi/models"
)

// ValidateRegistrationEmailNoContentCode is the HTTP code returned for type ValidateRegistrationEmailNoContent
const ValidateRegistrationEmailNoContentCode int = 204

/*ValidateRegistrationEmailNoContent The server successfully processed the request and is not returning any content.

swagger:response validateRegistrationEmailNoContent
*/
type ValidateRegistrationEmailNoContent struct {
}

// NewValidateRegistrationEmailNoContent creates ValidateRegistrationEmailNoContent with default headers values
func NewValidateRegistrationEmailNoContent() *ValidateRegistrationEmailNoContent {

	return &ValidateRegistrationEmailNoContent{}
}

// WriteResponse to the client
func (o *ValidateRegistrationEmailNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*ValidateRegistrationEmailDefault - 409.700: email is not available
- 422.703: wrong captcha answer


swagger:response validateRegistrationEmailDefault
*/
type ValidateRegistrationEmailDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewValidateRegistrationEmailDefault creates ValidateRegistrationEmailDefault with default headers values
func NewValidateRegistrationEmailDefault(code int) *ValidateRegistrationEmailDefault {
	if code <= 0 {
		code = 500
	}

	return &ValidateRegistrationEmailDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the validate registration email default response
func (o *ValidateRegistrationEmailDefault) WithStatusCode(code int) *ValidateRegistrationEmailDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the validate registration email default response
func (o *ValidateRegistrationEmailDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the validate registration email default response
func (o *ValidateRegistrationEmailDefault) WithPayload(payload *models.Error) *ValidateRegistrationEmailDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the validate registration email default response
func (o *ValidateRegistrationEmailDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ValidateRegistrationEmailDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
